name: CI Pipeline
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  all_checks:
    name: Checkstyle -> Compile -> Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Clean
        run: mvn -ntp clean
      - name: Build
        run: mvn -ntp compile
      - name: Run Tests
        run: mvn -ntp test
